WebApplication3/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }
    }
}

WebApplication3/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;
using System.Net.NetworkInformation;
using System.Text.RegularExpressions;

namespace WebApplication3.ViewModels
{
    public class Register
    {

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string FirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string NRIC { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public string DOB { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public string Resume { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string WhoAmI { get; set; }
    }
}

WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication3/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }
        private readonly SignInManager<ApplicationUser> signInManager;
        public LoginModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                LModel.RememberMe, false);
                if (identityResult.Succeeded)
                {
                }
                ModelState.AddModelError("", "Username or Password incorrect");
            }
            return Page();
        }
    }
}

WebApplication3/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Model;

namespace WebApplication3.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public IActionResult OnPostDontLogout()
        {
            return RedirectToPage("Index");
        }
    }
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/Register.cshtml.cs
using hbehr.recaptcha;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Options;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
    public class RegisterModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }
        [BindProperty]
        public Register RModel { get; set; }
        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }



        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");
                var user = new ApplicationUser()
                {
                    Email = RModel.Email,
                    FirstName = RModel.FirstName,
                    LastName = RModel.LastName,
                    NRIC = protector.Protect(RModel.NRIC),
                    DOB = RModel.DOB,
                };
                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return Page();
        }
    }
}

WebApplication3/Pages/Index.cshtml
@page
@model IndexModel
@inject IHttpContextAccessor contxt;
@{
    ViewData["Title"] = "Ace Job Agency";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <ul>
        <li> Student id: @contxt.HttpContext.Session.GetString("StudentName")</li>
        <li> Student Name: @contxt.HttpContext.Session.GetInt32("StudentId")</li>
    </ul>
    <form asp-controller="Home" asp-action="Index" method="post" asp-antiforgery="true">
        <input name="txtname" type="Text" />
        <input type="Submit" value="Submit" />
    </form>
</div>
<div>
    @functions {
        public int divide(int x, int y)
        {
            string errormessage;
            try
            {
                return x / y;
            }
            catch (DivideByZeroException d)
            {
                errormessage = d.ToString();
                WriteLiteral("<br />Cannot Divide by Zero Exception found <br /><br />");
                WriteLiteral("Additional Info <br /><br />" + errormessage);
                return 0;
            }
        }
    }
    <h3>Division of 10 / 5 is @divide(10, 5)</h3>
    <h3>Division of 10 / 0 is @divide(12, 0)</h3>

</div>

WebApplication3/Pages/Login.cshtml
@page
@model WebApplication3.Pages.LoginModel
@{
    <div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post">
				
				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="Text" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button type="submit" class="btn btn-primary">Login</button>
				</div>
			</form>
		</div>
	</div>
</div>
}

WebApplication3/Pages/Logout.cshtml
@page
@model WebApplication3.Pages.LogoutModel
@{
}
<form method="post">
    <div class="container mt-5">

        <div class="row justify-content-center align-items-center">

            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn_primary" asp-page-handler="Logout"> Yes</button>
                    <button class="btn btn_light ml-5 border-dark" asp-page-handler="DontLogout"> No</button>
                </p>
            </div>
        </div>
    </div>
</form>

WebApplication3/Pages/Register.cshtml
@page
@using Microsoft.Extensions.Options
@using WebApplication3.Model
@model WebApplication3.Pages.RegisterModel
<head>
    <script src='https://www.google.com/recaptcha/api.js'></script>   
</head>
<body>
    <div class="container mt-5">

        <div class="row justify-content-center align-items-center">

            <div class="col-sm-12 col-md-12 col-lg-4">
                <h1 class="mb-3">Register </h1>

                <form method="post">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.FirstName">First Name</label>
                        <input type="Text" asp-for="RModel.FirstName" class="form-control" />
                        <span asp-validaton-for="RModel.FirstName" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.LastName">Last Name</label>
                        <input type="Text" asp-for="RModel.LastName" class="form-control" />
                        <span asp-validaton-for="RModel.LastName" class="text-danger"></span>
                    </div>

                    <div class="col-md-6 mb-4">

                        <h6 class="mb-2 pb-1">Gender: </h6>

                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender"
                                   value="option1" checked />
                            <label class="form-check-label" for="femaleGender">Female</label>
                        </div>

                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"
                                   value="option2" />
                            <label class="form-check-label" for="maleGender">Male</label>
                        </div>

                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="otherGender"
                                   value="option3" />
                            <label class="form-check-label" for="otherGender">Other</label>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.NRIC">NRIC</label>
                        <input type="Text" asp-for="RModel.NRIC" class="form-control" />
                        <span asp-validaton-for="RModel.NRIC" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.Email">Email Address</label>
                        <input type="Text" asp-for="RModel.Email" class="form-control" />
                        <span asp-validaton-for="RModel.Email" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.Password">Password</label>
                        <input type="Text" asp-for="RModel.Password" class="form-control" />
                        <span asp-validaton-for="RModel.Password" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                        <input type="Text" asp-for="RModel.ConfirmPassword" class="form-control" />
                        <span asp-validaton-for="RModel.ConfirmPassword" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.DOB">Date Of Birth</label>
                        <input type="Date" asp-for="RModel.DOB" class="form-control" />
                        <span asp-validaton-for="RModel.DOB" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.Resume">Resume</label>
                        <input type="file" asp-for="RModel.Resume" class="form-control" />
                        <span asp-validaton-for="RModel.Resume" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label class="form-label" asp-for="RModel.WhoAmI">WhoAmI</label>
                        <input type="MuText" asp-for="RModel.WhoAmI" class="form-control" />
                        <span asp-validaton-for="RModel.WhoAmI" class="text-danger"></span>
                    </div>


                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">
                            Register
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>